# Generated by Django 5.2 on 2025-05-08 21:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0003_ubicacion'),
        ('shared_models', '0009_alter_empresa_rif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventario_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Inventario')),
                ('lote', models.CharField(blank=True, help_text='Número de lote para trazabilidad', max_length=50, null=True, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del lote', null=True, verbose_name='Fecha de Vencimiento')),
                ('estado_lote', models.CharField(choices=[('disponible', 'Disponible'), ('cuarentena', 'En cuarentena'), ('bloqueado', 'Bloqueado'), ('vencido', 'Vencido'), ('agotado', 'Agotado')], default='disponible', help_text='Estado actual del lote', max_length=20, verbose_name='Estado del Lote')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad total disponible', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('cantidad_reservada', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad reservada para pedidos en proceso', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Reservada')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario de adquisición', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este inventario', null=True, verbose_name='Notas')),
                ('metadatos', models.JSONField(blank=True, help_text='Metadatos flexibles sin necesidad de modificar el esquema', null=True, verbose_name='Metadatos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_ultimo_movimiento', models.DateTimeField(blank=True, help_text='Fecha del último movimiento de este inventario', null=True, verbose_name='Fecha de Último Movimiento')),
                ('almacen', models.ForeignKey(help_text='Almacén donde se encuentra el inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='almacenes.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(help_text='Producto al que pertenece este inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='shared_models.producto', verbose_name='Producto')),
                ('ubicacion', models.ForeignKey(blank=True, help_text='Ubicación específica dentro del almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='almacenes.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['almacen', 'producto', 'fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Movimiento')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('traslado', 'Traslado'), ('ajuste', 'Ajuste'), ('reserva', 'Reserva'), ('liberacion', 'Liberación')], help_text='Tipo de movimiento realizado', max_length=20, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento', verbose_name='Fecha')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad involucrada en el movimiento', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('es_incremento', models.BooleanField(default=True, help_text='Indica si el movimiento incrementa o reduce el inventario', verbose_name='Es Incremento')),
                ('referencia', models.CharField(blank=True, help_text='Referencia externa (ej: número de pedido, factura, etc.)', max_length=100, null=True, verbose_name='Referencia')),
                ('codigo_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único para seguimiento del movimiento', verbose_name='Código de Seguimiento')),
                ('usuario', models.CharField(blank=True, help_text='Usuario que realizó el movimiento', max_length=100, null=True, verbose_name='Usuario')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este movimiento', null=True, verbose_name='Notas')),
                ('inventario', models.ForeignKey(help_text='Inventario al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventarios.inventario', verbose_name='Inventario')),
                ('ubicacion_destino', models.ForeignKey(blank=True, help_text='Ubicación de destino para traslados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='almacenes.ubicacion', verbose_name='Ubicación Destino')),
                ('ubicacion_origen', models.ForeignKey(blank=True, help_text='Ubicación de origen para traslados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='almacenes.ubicacion', verbose_name='Ubicación Origen')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['producto', 'almacen'], name='inventarios_product_f439d4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['almacen', 'ubicacion'], name='inventarios_almacen_ec2661_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['producto', 'estado_lote'], name='inventarios_product_0ad4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['fecha_vencimiento'], name='inventarios_fecha_v_765340_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'almacen', 'ubicacion', 'lote')},
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha'], name='inventarios_fecha_f8e4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='inventarios_tipo_1c5499_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['referencia'], name='inventarios_referen_e6fe01_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['codigo_seguimiento'], name='inventarios_codigo__fba0fb_idx'),
        ),
    ]
