# Generated by Django 5.2 on 2025-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_productoalimento_productoelectronico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoalimento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productoalimento',
            name='categoria_alimento',
            field=models.CharField(choices=[('lacteo', 'Lácteo'), ('carne', 'Carne'), ('pescado', 'Pescado'), ('fruta', 'Fruta'), ('verdura', 'Verdura'), ('cereal', 'Cereal'), ('legumbre', 'Legumbre'), ('bebida', 'Bebida'), ('snack', 'Snack'), ('congelado', 'Congelado'), ('enlatado', 'Enlatado'), ('panaderia', 'Panadería'), ('otro', 'Otro')], default='otro', help_text='Categoría específica del alimento', max_length=20, verbose_name='Categoría de Alimento'),
        ),
    ]
