# Generated by Django 5.2 on 2025-05-07 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('unidad_medida', models.CharField(choices=[('Kg', 'Kilogramos'), ('unidades', 'Unidades'), ('Cajas', 'Cajas'), ('Lts', 'Litros')], max_length=10, verbose_name='Unidad de Medida')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('alerta_stock', models.PositiveIntegerField(default=5, verbose_name='Alerta de Stock')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
