# Generated by Django 5.2 on 2025-05-07 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_producto_exento_iva_producto_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Cliente')),
                ('tipo', models.CharField(choices=[('juridico', 'Jurídico'), ('natural', 'Natural')], max_length=10, verbose_name='Tipo de Cliente')),
                ('rif', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El RIF debe tener el formato: V/E/J/G seguido de 9 dígitos.', regex='^[VEJG][0-9]{9}$')], verbose_name='RIF')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('pais', models.CharField(default='Venezuela', max_length=50, verbose_name='País')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
