# Generated by Django 5.2 on 2025-05-08 14:05

from django.db import migrations

def crear_monedas_iniciales(apps, schema_editor):
    """
    Crea las monedas iniciales necesarias para la migración.
    """
    Moneda = apps.get_model('shared_models', 'Moneda')

    # Crear moneda Bolívares (como moneda base)
    bolivares, created = Moneda.objects.get_or_create(
        nombre='Bolivares',
        defaults={
            'simbolo': 'Bs.',
            'es_base': True,
            'tasa_oficial': 1.0,
            'tasa_mercado': 1.0
        }
    )

    # Crear moneda Dólares
    dolares, created = Moneda.objects.get_or_create(
        nombre='USD',
        defaults={
            'simbolo': '$',
            'es_base': False,
            'tasa_oficial': 35.0,  # Valor ejemplo, debe ajustarse
            'tasa_mercado': 36.0   # Valor ejemplo, debe ajustarse
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_create_moneda_model'),
    ]

    operations = [
        migrations.RunPython(crear_monedas_iniciales),
    ]
