# Generated by Django 5.2 on 2025-05-08 14:07

from django.db import migrations, models
import django.db.models.deletion

def actualizar_productos_moneda(apps, schema_editor):
    """
    Actualiza los productos para usar las nuevas monedas.
    """
    Producto = apps.get_model('shared_models', 'Producto')
    Moneda = apps.get_model('shared_models', 'Moneda')

    # Obtener las monedas
    try:
        bolivares = Moneda.objects.get(nombre='Bolivares')
        dolares = Moneda.objects.get(nombre='USD')

        # Actualizar productos con moneda 'Bolivares'
        for producto in Producto.objects.filter(moneda_old='Bolivares'):
            producto.moneda = bolivares
            producto.save(update_fields=['moneda'])

        # Actualizar productos con moneda 'USD'
        for producto in Producto.objects.filter(moneda_old='USD'):
            producto.moneda = dolares
            producto.save(update_fields=['moneda'])

    except Moneda.DoesNotExist:
        # Si no existen las monedas, no hacemos nada
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0005_add_initial_monedas'),
    ]

    operations = [
        # Primero, renombramos el campo actual para no perder los datos
        migrations.RenameField(
            model_name='producto',
            old_name='moneda',
            new_name='moneda_old',
        ),

        # Luego, añadimos el nuevo campo ForeignKey
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(
                help_text='Moneda en la que se expresan los precios del producto',
                null=True,  # Temporalmente permitimos NULL
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos',
                to='shared_models.moneda',
                verbose_name='Moneda'
            ),
        ),

        # Ejecutamos la función para migrar los datos
        migrations.RunPython(actualizar_productos_moneda),

        # Finalmente, eliminamos el campo antiguo y hacemos que el nuevo sea obligatorio
        migrations.RemoveField(
            model_name='producto',
            name='moneda_old',
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(
                help_text='Moneda en la que se expresan los precios del producto',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos',
                to='shared_models.moneda',
                verbose_name='Moneda'
            ),
        ),
    ]
