# Generated by Django 5.2 on 2025-05-08 14:29

import django.db.models.deletion
import shared_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_update_producto_moneda_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(default=shared_models.models.get_moneda_base_id, help_text='Moneda en la que se expresan los precios del producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='shared_models.moneda', verbose_name='Moneda'),
        ),
    ]
