# Generated by Django 5.2 on 2025-05-08 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0008_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rif',
            field=models.CharField(help_text='Registro de Información Fiscal', max_length=10, validators=[django.core.validators.RegexValidator(message='El RIF debe tener el formato: J/V/G seguido de - seguido de 8 dígitos.', regex='^[JVG]-[0-9]{8}$')], verbose_name='RIF'),
        ),
    ]
