# Generated by Django 5.2 on 2025-05-09 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0009_alter_empresa_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='actualizado_por',
            field=models.CharField(blank=True, help_text='Usuario que actualizó por última vez el registro', max_length=50, null=True, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoría general del producto', max_length=50, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras del producto (EAN, UPC, etc.)', max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=50, null=True, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_inventariable',
            field=models.BooleanField(default=True, help_text='Indica si el producto se gestiona en inventario', verbose_name='Es Inventariable'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('descontinuado', 'Descontinuado'), ('agotado', 'Agotado'), ('suspendido', 'Suspendido'), ('borrador', 'Borrador')], default='activo', help_text='Estado actual del producto', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='metadatos',
            field=models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_mayorista',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio para ventas al por mayor', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mayorista'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo permitido para ventas', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mínimo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - Código interno de gestión', max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad máxima recomendada en inventario', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Subcategoría del producto', max_length=50, null=True, verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas para facilitar búsquedas', max_length=200, null=True, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_impuesto',
            field=models.CharField(choices=[('exento', 'Exento'), ('general', 'General'), ('reducido', 'Reducido'), ('adicional', 'Adicional')], default='general', help_text='Tipo de impuesto aplicable al producto', max_length=20, verbose_name='Tipo de Impuesto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alerta_stock',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Cantidad mínima antes de generar alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alerta de Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, help_text='Costo de adquisición o producción', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del producto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='exento_iva',
            field=models.BooleanField(default=False, help_text='Indica si el producto está exento de IVA', verbose_name='Exento de IVA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del producto', max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre comercial del producto', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta al público', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidades'), ('caja', 'Cajas'), ('paquete', 'Paquetes'), ('docena', 'Docenas'), ('m', 'Metros'), ('cm', 'Centímetros'), ('m2', 'Metros cuadrados'), ('m3', 'Metros cúbicos'), ('par', 'Pares'), ('rollo', 'Rollos'), ('hora', 'Horas'), ('servicio', 'Servicio'), ('otro', 'Otro')], help_text='Unidad de medida para el producto', max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='shared_mode_nombre_ec16d2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='shared_mode_codigo_572765_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='shared_mode_estado_50e611_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='shared_mode_categor_e1116c_idx'),
        ),
    ]
