# Generated by Django 5.2 on 2025-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('almacen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Almacén')),
                ('nombre', models.CharField(help_text='Nombre identificativo del almacén', max_length=100, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(help_text='Dirección física o ubicación del almacén', max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre el almacén', null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
    ]
