# Generated by Django 5.2 on 2025-05-08 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el almacén está activo o no', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área total del almacén en metros cuadrados', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área Total (m²)'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='capacidad_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad máxima del almacén', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad Máxima'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='capacidad_utilizada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad actualmente utilizada (calculada o manual)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad Utilizada'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='ciudad',
            field=models.CharField(default='Maracaibo', help_text='Ciudad donde se encuentra el almacén', max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal para envíos y recepción de mercancía', max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='coordenadas_gps',
            field=models.CharField(blank=True, help_text="Latitud y longitud para ubicación exacta (formato: 'lat,lng')", max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Las coordenadas deben tener el formato 'latitud,longitud'", regex='^-?\\d+(\\.\\d+)?,-?\\d+(\\.\\d+)?$')], verbose_name='Coordenadas GPS'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='Email para comunicaciones relacionadas con el almacén', max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='fecha_apertura',
            field=models.DateField(blank=True, help_text='Fecha en que comenzó a operar el almacén', null=True, verbose_name='Fecha de Apertura'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='fecha_cierre',
            field=models.DateField(blank=True, help_text='Fecha de cierre (si aplica)', null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='horario_operacion',
            field=models.CharField(blank=True, help_text='Horario de funcionamiento del almacén (ej. L-V 9am-5pm)', max_length=100, null=True, verbose_name='Horario de Operación'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='metadatos',
            field=models.JSONField(blank=True, help_text='Metadatos flexibles sin necesidad de modificar el esquema', null=True, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='notas_operativas',
            field=models.TextField(blank=True, help_text='Notas especiales sobre la operación del almacén', null=True, verbose_name='Notas Operativas'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='pais',
            field=models.CharField(default='Venezuela', help_text='País donde se encuentra el almacén', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Persona encargada del almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador para URLs amigables', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del almacén', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tipo_almacen',
            field=models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('transito', 'Tránsito'), ('devolucion', 'Devolución'), ('otro', 'Otro')], default='principal', help_text='Tipo o categoría del almacén', max_length=20, verbose_name='Tipo de Almacén'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='unidad_medida_capacidad',
            field=models.CharField(choices=[('m3', 'Metro cúbico'), ('kg', 'Kilogramo'), ('pallet', 'Pallet'), ('unidad', 'Unidad'), ('otro', 'Otro')], default='m3', help_text='Unidad en que se mide la capacidad', max_length=10, verbose_name='Unidad de Medida de Capacidad'),
        ),
    ]
