# Generated by Django 5.2 on 2025-05-08 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_almacen_activo_almacen_area_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('ubicacion_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Ubicación')),
                ('codigo', models.CharField(help_text='Código único de la ubicación dentro del almacén (ej: A-01-02-03)', max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la ubicación (ej: Estantería A, Pasillo 1, Nivel 2, Posición 3)', max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('zona', 'Zona'), ('pasillo', 'Pasillo'), ('estanteria', 'Estantería'), ('nivel', 'Nivel'), ('posicion', 'Posición'), ('otro', 'Otro')], default='zona', help_text='Tipo o categoría de la ubicación', max_length=20, verbose_name='Tipo de Ubicación')),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad máxima de la ubicación', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad')),
                ('unidad_medida_capacidad', models.CharField(choices=[('m3', 'Metro cúbico'), ('kg', 'Kilogramo'), ('pallet', 'Pallet'), ('unidad', 'Unidad'), ('otro', 'Otro')], default='unidad', help_text='Unidad en que se mide la capacidad', max_length=10, verbose_name='Unidad de Medida de Capacidad')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la ubicación está activa o no', verbose_name='Activa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la ubicación', null=True, verbose_name='Descripción')),
                ('metadatos', models.JSONField(blank=True, help_text='Metadatos flexibles sin necesidad de modificar el esquema', null=True, verbose_name='Metadatos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('almacen', models.ForeignKey(help_text='Almacén al que pertenece esta ubicación', on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='almacenes.almacen', verbose_name='Almacén')),
                ('padre', models.ForeignKey(blank=True, help_text='Ubicación que contiene a esta ubicación (para crear jerarquía)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='almacenes.ubicacion', verbose_name='Ubicación Padre')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['almacen', 'codigo'],
                'unique_together': {('almacen', 'codigo')},
            },
        ),
    ]
